t = open('dev_content.py').read()
missing = []
def rep(a, b, count=1):
    global t
    if a not in t: missing.append(a[:90]); return
    t = t.replace(a, b, count)
rep('import code_facts as cf\n', 'import code_facts as cf\nimport dev12_sections as ns\n')
rep('"""Developer guide content (block list). Reference sections are generated from the real source, tables and scripts."""', '"""Developer guide v1.2 content (block list). Reference sections are generated from the real source, tables and scripts; sections 1.4, 1.5 and 15 to 19 are in dev12_sections.py."""')
rep('so they match what is deployed in the MC tenant at the time of writing.")', 'so they match what is deployed in the MC tenant at the time of writing. Version 1.2 adds the maker-checker workflow, the dashboard, notifications, the staff portal and an analysis of PA001 and iHub (sections 15 to 19). **Section 1.4 lists what is most likely to surprise a new developer: read it first.**")')
rep('P("A set of 13 REST APIs (12 active, 1 retired) written as iComposer Groovy scripts on the InsureMO platform.', 'P("A set of 18 active REST APIs (and 2 inactive ones: a retired stub and a test probe) with 13 shared functions, written as iComposer Groovy scripts on the InsureMO platform, plus a staff portal (a UIC page).')
rep('Everything that a business user may want to change (validation rules, product data, refund rules, texts, formats, channels, insurers) is data in iTables, not code.")', 'Bank staff work in three roles (Maker, Proposal Checker, Cancellation Checker) through the portal. Everything that a business user may want to change (validation rules, product data, refund rules, texts, formats, channels, insurers, users and roles, message texts) is data in iTables, not code. The solution is developed in iComposer only: iHub is not used (section 18).")')
rep('    ["Checker / Approver", "The two roles of the cancellation: the Checker creates the request, the Approver decides it."],', '''    ["Maker", "Bank employee who creates quotations and proposals and raises cancellation requests."],
    ["Proposal Checker", "Bank employee who approves (issues) or rejects a submitted proposal."],
    ["Cancellation Checker", "Bank employee who approves or rejects a cancellation request (named Approver in v1.0 of the cancellation API)."],
    ["AgentCode", "Platform proposal field in which the maker's platform user id is stored (section 15.3)."],
    ["SNS", "The platform's notification service used to send email and SMS (section 16)."],
    ["UIC", "InsureMO UI Connector: hosts the portal as a single-page web app (section 17)."],
    ["Dry run", "Notification mode in which messages are recorded in the response but not sent."],''')
rep('# ================================================================== 2\nH1("2. Architecture")', 'ns.read_first(globals())\n# ================================================================== 2\nH1("2. Architecture")')
rep('FIG("arch", "Figure 1: Architecture — channel, gateway, iComposer APIs, common functions, platform services and tables")', 'FIG("arch2", "Figure 1: Architecture (v1.2) — channels, gateway, iComposer APIs, common functions, platform services and tables")')
rep('they are changed with the `imo` tool by an administrator.")', 'they are changed with the `imo` tool by an administrator. From v1.2 the API also checks the caller\'s role (`UPAccess`) and the platform search index is read for queues and the dashboard (`UPWorklist`).")')
rep('     "One error contract on every API: `status`, `code`, `message`, `errors[]`, `api`, `trace_id`."])', '     "One error contract on every API: `status`, `code`, `message`, `errors[]`, `api`, `trace_id`. A missing role or a maker-checker breach is 403 `UP-403`.",\n     "Roles come from the table `UP_UserRole` and are checked in the APIs, never in the portal alone. The portal menu is a convenience.",\n     "No workflow state is kept in our own tables: proposals and cancellation requests are read from the platform (section 15)."])')
rep('     "State and ownership checks for existing records: record exists (404),', '     "Role check: `UPAccess.require(...)` (403 `UP-403`), then for approvals the maker-checker rule. State and ownership checks for existing records: record exists (404),')
rep('"`UPShaper.shapeResponse`: commission switch, premium fields, payment info restored, CarrierCode / CarrierName added.",', '"`UPShaper.shapeResponse`: commission switch, premium fields, payment info restored, CarrierCode / CarrierName added. Then, where the action triggers one, `UPNotify.fire` adds `Notifications[]`.",')
rep('api/<Name>/<Name>.groovy         13 API scripts (UPCancelPolicy is a retired stub, status inactive)\\n    function/<Name>/<Name>.groovy    10 common functions', 'api/<Name>/<Name>.groovy         20 API scripts (18 active; UPCancelPolicy is a retired stub and UPSpikeWho a probe, both inactive)\\n    function/<Name>/<Name>.groovy    13 common functions')
rep('  tests/ security/ carrier/          test cases and results")', '  tests/ security/ carrier/ workflow/ test cases and results\\nuic_pages/uponly/portal/sohar-insurance-portal/   the portal (index.html, metadata.json, prompt.md) in the git repository\\ndeliverables/workflow_src/           v1.2 iComposer source, set-up and test scripts (git copy)")')
rep('APIs are POST except `UPLoadPolicy` (GET). All paths are `/up/<name>`: get-plans, proposal, update-proposal, issue, load-policy, proposal-reject, doc_generation, application_doc_generation, cancel-check, cancel-approve, list-master-table, commission-query, generate-feedfile (and the inactive cancel-policy).', 'APIs are POST except `UPLoadPolicy` and `UPMe` (GET). All paths are `/up/<name>`: get-plans, proposal, update-proposal, issue, load-policy, proposal-reject, doc_generation, application_doc_generation, cancel-check, cancel-approve, list-master-table, commission-query, generate-feedfile, and since v1.2 me, worklist (`UPWorklistApi`), dashboard, share, cancel-detail (the inactive ones are cancel-policy and spike-who).')
rep('     "Keep each function focused; the largest file is `UPValidator` (333 lines)."])', '     "`UPShaper.shapeResponse` returns `Object`: cast it (`(Map<String, Object>) shaper.shapeResponse(r)`) before adding fields. The SNS email and SMS builders take `requestBody(...)`; an anonymous `Comparator` must not use method variables; the accessor of a hyphenated SDK tag is camel case (`emailAccountApi()`).",\n     "Empty lists are dropped from the JSON that the platform returns (for example `Roles` in `/up/me`): treat a missing list as empty.",\n     "Keep each function focused; the largest file is `UPValidator`."])')
rep('Push in this order (the same order is used for UAT): UPDataUtil, UPSecurity, UPErrorHandler, UPPlatformClient, UPValidator, UPProductData, UPShaper, UPDocBuilder, UPDocService, UPCancelService, then the 12 active APIs.', 'Push in this order (the same order is used for UAT): UPDataUtil, UPSecurity, UPErrorHandler, UPPlatformClient, UPValidator, UPProductData, UPShaper, UPDocBuilder, UPDocService, UPAccess, UPNotify, UPWorklist, UPCancelService, then the 18 active APIs. The tables `UP_UserRole` and `UP_NotifyTemplate` and the new configuration keys must exist before the new code runs.')
rep('TBL(["API", "Flow in code"], [[a, b] for a, b in W], [20, 80])', 'W = ns_walk + W\nTBL(["API", "Flow in code"], [[a, b] for a, b in W], [20, 80])')
rep('W = [\n ("UPGetPlans"', 'ns_walk = [\n ("v1.2 changes to existing APIs", "UPProposal: `UPAccess.require(Maker)`, `prepareProposal`, then `AgentCode` = caller id, create, shape, `UPNotify.fire(\\"SUBMITTED\\")`, `Notifications[]` added. UPUpdateProposal: Maker and creator only (`requireCreator`), keeps the stored AgentCode. UPIssue: Proposal Checker, `requireNotCreator(existing.AgentCode)`, after the issue `PROPOSAL_ISSUED` to the maker and the customer (contact from the raw loaded proposal). UPProposalReject: Proposal Checker, not the creator, `ProposalRejectDesc` is required by a field rule, `PROPOSAL_REJECTED` to the maker. UPCancelCheck: Maker; a new request sends `CANCEL_REQUESTED`. UPCancelApprove: Cancellation Checker; `UPCancelService.decide` compares the requester (`DataEntryUserId` of the pending endorsement) with the caller and sends `CANCEL_APPROVED` / `CANCEL_REJECTED`. UPGetPlans, UPLoadPolicy, UPDocGeneration, UPApplicationDocGeneration and UPCommissionQuery call `requireAny()`."),\n ("UPMe", "`UPAccess.me()`; no validation, no role needed."),\n ("UPWorklistApi", "Validates (`UP_FieldRule` rows for api name `UPWorklist`), role by Type, then `UPWorklist.proposalList` (PROPOSAL, MINE) or `cancellationList`. Section 15.4."),\n ("UPDashboard", "Validates, `requireAny()`, forces own figures for a maker-only caller, checks the window, then `UPWorklist.summary` or `commissionSection`. Section 15.5."),\n ("UPShare", "Validates, `requireAny()`, builds the placeholders (quotation: from `Details`; proposal / policy: loaded and channel-checked), takes the contact from the request or the stored record and calls `UPNotify.fire(event, ..., onlyChannel)`. Section 16."),\n ("UPCancelDetail", "Validates, Maker or Cancellation Checker, `UPCancelService.detail`: resolves the policy, finds the pending endorsement (signed policy id), recalculates the refund, returns requester, reason and `CanDecide`; creates nothing; 404 when no request is pending.")]\nW = [\n ("UPGetPlans"')
rep('"UP_Carrier": ("Insurers (CarrierCode, CarrierName, IsActive); linked from UP_ProductMaster.CarrierCode.", "UPProductData.carrierOf")}', '"UP_Carrier": ("Insurers (CarrierCode, CarrierName, IsActive); linked from UP_ProductMaster.CarrierCode.", "UPProductData.carrierOf"),\n        "UP_UserRole": ("Staff roles: UserRoleKey (user|ROLE), UserName, UserId (platform id), Role (MAKER / PROPOSAL_CHECKER / CANCELLATION_CHECKER), DisplayName, Branch, Email, Mobile, IsActive. Never exposed through master data.", "UPAccess"),\n        "UP_NotifyTemplate": ("Email / SMS texts per event, recipient and channel (TemplateKey, Event, Recipient, Channel, Subject, Body, SmsTemplateCode, IsActive).", "UPNotify")}')
rep('"PolicyNo, PolicyId, PolicyElementId, ProposalStatus, PolicyStatus", "ServerOwnedFields"]', '"PolicyNo, PolicyId, PolicyElementId, ProposalStatus, PolicyStatus, AgentCode (v1.2: the maker stamp)", "ServerOwnedFields"]')
rep('P("The request is the platform\'s own pending cancellation endorsement; its number is the `RequestNo`.")', 'P("The request is the platform\'s own pending cancellation endorsement; its number is the `RequestNo`. From v1.2 the Checker step is the **Maker** role and the Approver step the **Cancellation Checker** role (the code and routes are unchanged); the requester cannot decide their own request; `cancel-detail` shows a pending request without creating one; and the steps send alerts (section 16).")')
rep('["Not found", "`errorHandler.notFound(api, msg)`", "404 `UP-404`"],', '["Missing role / maker-checker breach", "`IllegalArgumentException(\\"FORBIDDEN:...\\")` from `UPAccess`", "403 `UP-403`, texts `MsgForbidden`, `MsgSelfApproval`, `MsgNotOwner`"], ["Not found", "`errorHandler.notFound(api, msg)`", "404 `UP-404`"],')
rep('for t, steps in rec: LBL(t); NUM(steps)', 'rec += [\n ("Add a user or change a role", ["Section 19.2: rows in `UP_UserRole` (`record-batch-save` / `record-save`); no deployment."]),\n ("Change a message text or add an event", ["Edit the `Subject` / `Body` of the row in `UP_NotifyTemplate` (`record-save`). For a new event add rows (TemplateKey = Event|Recipient|Channel) and call `notify.fire(\\"EVENT\\", notify.paramsOf(policy, extra), customer, makerUserId, \\"\\")` from the API; add the placeholders to `paramsOf` if needed."]),\n ("Send real email / SMS", ["Section 16.5."]),\n ("Add a menu item or screen to the portal", ["Add a `<section class=\\"view\\" id=\\"v_x\\">` and an entry in `NAV` (roles list or null for all); load its data in `go()`; call the API through `api()`; add a browser check to `flow2.js`; push with `imo uic page push`."]),\n ("Add a column to a queue", ["Add the field to `UPWorklist.policyRow`, push `UPWorklist`, then add a column object to `colsProposal` / `colsCancel` in the portal."]),\n ("Turn role enforcement on or off, or allow self approval", ["`python3 setcfg.py RoleEnforcement Y|N` and `AllowSelfApproval Y|N` (section 19.1)."]),\n ("Apply the Sohar brand", ["Edit the variables in the first `:root` block of `index.html` (colours, font) and the text badge; push the page."])]\nfor t, steps in rec: LBL(t); NUM(steps)')
rep('"snapshot.py": "Read-only snapshot of PA001 related objects; compare `before` and `after` to prove PA001 is unchanged."}', '"snapshot.py": "Read-only snapshot of PA001 related objects; compare `before` and `after` to prove PA001 is unchanged.",\n         "role_check.py": "v1.2: 35 live checks of roles, maker-checker rule, queues, cancellation detail, notifications (dry run), share, dashboard; switches `UP_UserRole` rows and `AllowSelfApproval` during the run and restores them.",\n         "workflow_setup.py": "v1.2 set-up: creates `UP_UserRole`, `UP_NotifyTemplate` and the first configuration keys / field rules (`workflow_setup2..5.py` add the later keys and rules).",\n         "setcfg.py": "Changes `UP_ApiConfig` values with `record-save` and prints the old value.",\n         "refresh_devdata.py": "Rebuilds `devdata/assets.json` and `devdata/tables.json` offline for this guide."}')
rep('`dev_content.py` (this guide).")', '`dev_content12.py` + `dev12_sections.py` (this guide; the v1.1 generator is `dev_content.py`). Browser tests of the portal (`flow2.js`, `login.js`, `run.js`, Playwright) are described in section 17.6.")')
rep('In short: 10 functions and 12 APIs, 12 `UP_` tables with their rows,', 'In short: 13 functions and 18 APIs (v1.2), 14 `UP_` tables with their rows (v1.2 added `UP_UserRole` and `UP_NotifyTemplate`),')
rep('the ids of products, data tables and templates are tenant specific and must be re-resolved, not copied.")', 'the ids of products, data tables and templates are tenant specific and must be re-resolved, not copied. **The UAT plan was written for v1.1: for v1.2 also deploy the portal page, the two new tables, the new keys and rules, set up users and roles, and the SNS accounts (section 19).**")')
rep('["PDF templates", "The insurer name is not printed on the documents.", "Add `CarrierName` to the print data and the templates."]], [22, 46, 32])', '["PDF templates", "The insurer name is not printed on the documents.", "Add `CarrierName` to the print data and the templates."],\n    ["v1.2 items", "See the consolidated list in section 19.6 (notifications live, sign-in, portal URL, role checks on feed and master data, maker stamp, dashboard accuracy, documents).", "Section 19.6."]], [22, 46, 32])')
rep('# ================================================================== annex', 'ns.sections(globals())\n# ================================================================== annex')
open('dev_content12.py', 'w').write(t)
print("missing:", missing)
